spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  session:
    jdbc:
      initialize-schema: never
      table-name: SPRING_SESSION
    timeout: 1440m
  sql:
    init:
      mode: never
